# Generated by Django 4.2.3 on 2023-07-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='sdf', upload_to='pics'),
            preserve_default=False,
        ),
    ]
